### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by saltsoftdrink** [ShafSpecs/Nighty-Night-Theme#1]
How did you create this image (**https://raw.githubusercontent.com/ShafSpecs/Nighty-Night-Theme/main/image/nighty.png**)

**Comment by ShafSpecs** [comment]
I used https://desygner.com to create this particular image. And the VSCode extension CodeSnap for the code images

The image is simple a 3-layer photo. The first layer is the background color, the second layer is the photos and title, the third layer is just a gradient that is invisible at the top and `opacity: 1` at the bottom.

**Comment by saltsoftdrink** [comment]
Bro, I Also Have a Theme Named:- **Samyak Bumb Theme**. Over **500** Downloads.

https://marketplace.visualstudio.com/items?itemName=SamyakBumb.samyak.

Would You Like to Collaborate? ⚒️  💪

**Comment by ShafSpecs** [comment]
> Bro, I Also Have a Theme Named:- **Samyak Bumb Theme**. Over **500** Downloads.
> 
> https://marketplace.visualstudio.com/items?itemName=SamyakBumb.samyak.
> 
> Would You Like to Collaborate? ⚒️ 💪

Sure thing.

**Comment by saltsoftdrink** [comment]
> Sure thing.

Soo, Let's Goo

**Comment by ShafSpecs** [comment]
Let's connect via Twitter then 👍

**Comment by saltsoftdrink** [comment]
Sorry, Bro But I Don't Have Twitter.
I'm from **India**
Bro From which country your are?

**Comment by saltsoftdrink** [comment]
Hello where are you?

**Comment by ShafSpecs** [comment]
> Hello where are you?

I am fine thanks. Do you have a discord or any social media account we could use to discuss besides GitHub?

**Comment by saltsoftdrink** [comment]
Sorry, I don't have any social accounts. But first please create me that img. So, our both img will look same but theme will be different.

**Comment by saltsoftdrink** [comment]
I created Insta account now

**Comment by saltsoftdrink** [comment]
We will chat on it

**Comment by saltsoftdrink** [comment]
> > Hello where are you?
> 
> I am fine thanks. Do you have a discord or any social media account we could use to discuss besides GitHub?

Insta
https://www.instagram.com/ugyiubnh/

**Comment by saltsoftdrink** [comment]
> > Hello where are you?
> 
> I am fine thanks. Do you have a discord or any social media account we could use to discuss besides GitHub?

My Instagram
https://www.instagram.com/ugyiubnh/
